// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/quotecraft/Dashboard.tsx": () => import("../components/mockups/quotecraft/Dashboard.tsx"),
  "./components/mockups/quotecraft/PdfExport.tsx": () => import("../components/mockups/quotecraft/PdfExport.tsx"),
  "./components/mockups/quotecraft/QuoteScreen.tsx": () => import("../components/mockups/quotecraft/QuoteScreen.tsx"),
  "./components/mockups/quotecraft/Registration.tsx": () => import("../components/mockups/quotecraft/Registration.tsx"),
  "./components/mockups/quotecraft/VoiceProcessing.tsx": () => import("../components/mockups/quotecraft/VoiceProcessing.tsx")
};
